### PR TITLE
sets undefined index to empty string

### LINKED ISSUE #2: Undefined property notices when enabling module
I  enabled the module from within admin/modules and got a ton of error messages as it attempted to rebuild the sort data. Hmm, actually looks like the same 2 errors a zillion times (1,274 times each to be exact).

```
Notice: Undefined property: File::$name in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 146 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
Notice: Undefined property: File::$mime in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 146 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
```

Help?

### PR DESCRIPTION
**Pull request by keiserjb**

### CODE REVIEW

**Review by leeksoup — CHANGES_REQUESTED** [review]
I just tried this change. I still get the undefined property messages. I disabled / uninstalled the module, flushed the caches, then updated the code and re-enabled it.

I did some more debugging and figured out the problem. The code change you made needs to be on line 244, not 600. Line 244 is where it's set -- 600 just returns the values that have already been set.

When I make those edits, it runs clean and the error messages are gone.

I would be happy to commit the working version if you give me permissions to do so.

**Comment by leeksoup** [comment]
I just tried this change. I still get the undefined property messages. I disabled / uninstalled the module, flushed the caches, then updated the code and re-enabled it.

I did some more debugging and figured out the problem. The code change you made needs to be on line 244, not 600. Line 244 is where it's set -- 600 just returns the values that have already been set.

When I make those edits, it runs clean and the error messages are gone.

I would be happy to commit the working version if you give me permissions to do so.

**Comment by leeksoup** [comment]
Okay but it blows up later (on node save) now, so I'm going to do some more testing & debugging. The error message says:

```
Notice: Undefined variable: field_name in views_natural_sort_entity_to_vns() (line 600 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
```

The node save does happen successfully though.

Editing again to add more info. Looking at the line with the error and the lines before it, it doesn't make sense. The same variable ($field_name) is used 2 lines earlier with no error on that line (598).

**Comment by keiserjb** [comment]
Correct, I put it in the wrong place.  I think it needs to go both places.  I will look at it again.  The 'content' index of the array for the mime is null.  So this tries to make that an empty string.

**Comment by keiserjb** [comment]
I am closing this pr for a new one.

**Review by leeksoup — COMMENTED** [review]
Works. Fixes the undefined index notices reported.

**Comment by leeksoup** [comment]
Re comment at https://github.com/backdrop-contrib/views_natural_sort/pull/4#issuecomment-1484527988

That error message was caused by the use of $entity->$field_name on line 600. The correct value should have been $entity->$field, so removing that change from that line fixed it.

**Pull request closed without merging**
